name: build PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install pdflatex
      run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra

    - name: Build pdf
      run: make kactl

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "build PDF"
        branch: main

    - name: Copy PDF to pages
      run: |
        DIR=$(mktemp -d)
        cp kactl.pdf $DIR/kactl.pdf
        git switch gh-pages
        cp $DIR/kactl.pdf .
        git add .
        git commit -m "Update kactl.pdf"
        git push