name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Verify code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -r requirements.txt

    - run: oj-verify all
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
    
    # Build PDF

    - name: Install pdflatex
      run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra

    - name: Build pdf
      run: make kactl

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "build PDF"
        branch: main
