name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: Install pdflatex
      run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra
    - name: Build pdf
      run: make kactl
    # no need to test :)
    # - name: Run compiles
    #   run: make test-compiles
    # - name: Run stress tests
    #   run: make test
    - uses: stefanzweifel/git-auto-commit-action@v5
